version: "3.0"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8080:8080
    environment:
      SWAGGER_JSON: "/var/openapi-spec/spec.yml"
    volumes:
      - "./:/var/openapi-spec"